name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            backend/**
            frontend/**
          dir_names: true
          # This make sure you only get the parent folder
          dir_names_max_depth: 1
          matrix: true
      - name: Test output
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

  tag-release:
    name: tag-release
    runs-on: ubuntu-latest
    needs: changed-files
    strategy:
      matrix:
        dir: ${{ fromJson(needs.changed-files.outputs.changed-files) }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v4

      - name: Calculate release version
        id: calculate_new_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: true
          tag_prefix: ${{ matrix.dir }}/v
          github_token: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Kustomize Set Image - DEV
    #     run: |
    #       (
    #         cd manifests/overlays/dev;
    #         IMAGE=ghcr.io/${{ github.repository }}:${{ steps.calculate_new_version.outputs.new_tag }} ;
    #         kustomize edit set image $IMAGE
    #       )

    #   - name: Kustomize Set Image - PROD
    #     run: |
    #       (
    #         cd manifests/overlays/prod;
    #         IMAGE=ghcr.io/${{ github.repository }}:${{ steps.calculate_new_version.outputs.new_tag }} ;
    #         kustomize edit set image $IMAGE
    #       )

      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: jburns24/wedding-burns # Where to look for the trust policy <org>/<repo> (octo-sts must be installed on this repo)
          identity: push-tag # prefix of the trust policy expected to be at <scope>/.github/chainguard/<identity>.sts.yaml

    #   - name: Commit the updated manifests
    #     id: update-manifest
    #     run: |
    #       git config --global user.name '${{ github.actor }}'
    #       git config --global user.email '${{ github.actor }}@users.noreply.github.com'
    #       git config --global url."https://git:${{ steps.octo-sts.outputs.token }}@github.com".insteadOf "https://github.com"
    #       git commit -am "chore: bump image to ${{ needs.calculate_new_version.outputs.new_tag }} in manifests"
    #       git push
    #       echo "new_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Tag release
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
        #   dry_run: true
          custom_tag: ${{ steps.calculate_new_version.outputs.new_version }}
          github_token: ${{ steps.octo-sts.outputs.token }}
          tag_prefix: ${{ matrix.dir }}/v
          commit_sha: ${{ steps.update-manifest.outputs.new_sha }}
